[2023-03-18T08:15:14.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.check_endpoint manual__2023-03-18T08:15:13.431262+00:00 [queued]>
[2023-03-18T08:15:14.902+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.check_endpoint manual__2023-03-18T08:15:13.431262+00:00 [queued]>
[2023-03-18T08:15:14.902+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:15:14.902+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-18T08:15:14.902+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:15:14.921+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): check_endpoint> on 2023-03-18 08:15:13.431262+00:00
[2023-03-18T08:15:14.928+0000] {standard_task_runner.py:55} INFO - Started process 58228 to run task
[2023-03-18T08:15:14.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parking_spaces', 'check_endpoint', 'manual__2023-03-18T08:15:13.431262+00:00', '--job-id', '535', '--raw', '--subdir', 'DAGS_FOLDER/parking_spaces.py', '--cfg-path', '/tmp/tmp_1cx50yf']
[2023-03-18T08:15:14.937+0000] {standard_task_runner.py:83} INFO - Job 535: Subtask check_endpoint
[2023-03-18T08:15:15.043+0000] {task_command.py:388} INFO - Running <TaskInstance: parking_spaces.check_endpoint manual__2023-03-18T08:15:13.431262+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-18T08:15:15.149+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parking_spaces
AIRFLOW_CTX_TASK_ID=check_endpoint
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T08:15:13.431262+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T08:15:13.431262+00:00
[2023-03-18T08:15:15.239+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/melicharovykrecek/diploma/dags/parking_spaces.py", line 38, in check_endpoint
    raise ValueError('Endpoint not available')
ValueError: Endpoint not available
[2023-03-18T08:15:15.255+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=parking_spaces, task_id=check_endpoint, execution_date=20230318T081513, start_date=20230318T081514, end_date=20230318T081515
[2023-03-18T08:15:15.274+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 535 for task check_endpoint (Endpoint not available; 58228)
[2023-03-18T08:15:15.308+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T08:15:15.346+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
