[2023-03-18T08:15:11.109+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.check_endpoint scheduled__2023-03-18T07:00:00+00:00 [queued]>
[2023-03-18T08:15:11.128+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: parking_spaces.check_endpoint scheduled__2023-03-18T07:00:00+00:00 [queued]>
[2023-03-18T08:15:11.129+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:15:11.129+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-18T08:15:11.129+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T08:15:11.155+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): check_endpoint> on 2023-03-18 07:00:00+00:00
[2023-03-18T08:15:11.160+0000] {standard_task_runner.py:55} INFO - Started process 58210 to run task
[2023-03-18T08:15:11.168+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'parking_spaces', 'check_endpoint', 'scheduled__2023-03-18T07:00:00+00:00', '--job-id', '534', '--raw', '--subdir', 'DAGS_FOLDER/parking_spaces.py', '--cfg-path', '/tmp/tmpr5z1_3nq']
[2023-03-18T08:15:11.170+0000] {standard_task_runner.py:83} INFO - Job 534: Subtask check_endpoint
[2023-03-18T08:15:11.285+0000] {task_command.py:388} INFO - Running <TaskInstance: parking_spaces.check_endpoint scheduled__2023-03-18T07:00:00+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-18T08:15:11.390+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parking_spaces
AIRFLOW_CTX_TASK_ID=check_endpoint
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-18T07:00:00+00:00
[2023-03-18T08:15:11.599+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/melicharovykrecek/diploma/dags/parking_spaces.py", line 38, in check_endpoint
    raise ValueError('Endpoint not available')
ValueError: Endpoint not available
[2023-03-18T08:15:11.618+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=parking_spaces, task_id=check_endpoint, execution_date=20230318T070000, start_date=20230318T081511, end_date=20230318T081511
[2023-03-18T08:15:11.635+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 534 for task check_endpoint (Endpoint not available; 58210)
[2023-03-18T08:15:11.662+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-18T08:15:11.697+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
