[2023-03-17T17:46:50.325+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-17T17:46:46.572573+00:00 [queued]>
[2023-03-17T17:46:50.337+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-17T17:46:46.572573+00:00 [queued]>
[2023-03-17T17:46:50.338+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T17:46:50.338+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-17T17:46:50.338+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T17:46:50.353+0000] {taskinstance.py:1300} INFO - Executing <Task(MySqlOperator): create_table_parking_measurements> on 2023-03-17 17:46:46.572573+00:00
[2023-03-17T17:46:50.358+0000] {standard_task_runner.py:55} INFO - Started process 2377 to run task
[2023-03-17T17:46:50.369+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_file_from_endpoint', 'create_table_parking_measurements', 'manual__2023-03-17T17:46:46.572573+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmplo6ohd2g']
[2023-03-17T17:46:50.371+0000] {standard_task_runner.py:83} INFO - Job 218: Subtask create_table_parking_measurements
[2023-03-17T17:46:50.477+0000] {task_command.py:388} INFO - Running <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-17T17:46:46.572573+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-17T17:46:50.516+0000] {abstractoperator.py:609} ERROR - Exception rendering Jinja template for task 'create_table_parking_measurements', field 'sql'. Template: '/home/melicharovykrecek/diploma/sql/parking/measurements/create_table.sql'
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/melicharovykrecek/diploma/sql/parking/measurements/create_table.sql
[2023-03-17T17:46:50.518+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/melicharovykrecek/diploma/sql/parking/measurements/create_table.sql
[2023-03-17T17:46:50.533+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=get_file_from_endpoint, task_id=create_table_parking_measurements, execution_date=20230317T174646, start_date=20230317T174650, end_date=20230317T174650
[2023-03-17T17:46:50.550+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 218 for task create_table_parking_measurements (/home/melicharovykrecek/diploma/sql/parking/measurements/create_table.sql; 2377)
[2023-03-17T17:46:50.579+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T17:46:50.604+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
