[2023-03-16T21:37:48.175+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-16T21:36:58.915024+00:00 [queued]>
[2023-03-16T21:37:48.186+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-16T21:36:58.915024+00:00 [queued]>
[2023-03-16T21:37:48.186+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T21:37:48.186+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-16T21:37:48.187+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T21:37:48.201+0000] {taskinstance.py:1300} INFO - Executing <Task(MySqlOperator): create_table_parking_measurements> on 2023-03-16 21:36:58.915024+00:00
[2023-03-16T21:37:48.206+0000] {standard_task_runner.py:55} INFO - Started process 40515 to run task
[2023-03-16T21:37:48.213+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_file_from_endpoint', 'create_table_parking_measurements', 'manual__2023-03-16T21:36:58.915024+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpp6psm492']
[2023-03-16T21:37:48.215+0000] {standard_task_runner.py:83} INFO - Job 190: Subtask create_table_parking_measurements
[2023-03-16T21:37:48.311+0000] {task_command.py:388} INFO - Running <TaskInstance: get_file_from_endpoint.create_table_parking_measurements manual__2023-03-16T21:36:58.915024+00:00 [running]> on host diploma-vm.europe-west1-b.c.diploma-380314.internal
[2023-03-16T21:37:48.347+0000] {abstractoperator.py:609} ERROR - Exception rendering Jinja template for task 'create_table_parking_measurements', field 'sql'. Template: '/sql/parking/measurements/create_table.sql'
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /sql/parking/measurements/create_table.sql
[2023-03-16T21:37:48.351+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 602, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/melicharovykrecek/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /sql/parking/measurements/create_table.sql
[2023-03-16T21:37:48.368+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=get_file_from_endpoint, task_id=create_table_parking_measurements, execution_date=20230316T213658, start_date=20230316T213748, end_date=20230316T213748
[2023-03-16T21:37:48.387+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 190 for task create_table_parking_measurements (/sql/parking/measurements/create_table.sql; 40515)
[2023-03-16T21:37:48.427+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-16T21:37:48.450+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
